### PR TITLE
Open ox-hugo links in a new tab

### PR DESCRIPTION
**Pull request by AlexanderDavid**
When trying to open pdf files stored in the org dir I encountered a problem where they were trying to be opened as a stacked note. I modified the event handler to open a link in a new tab if the path includes the /ox-hugo/ folder. 

Please let me know if this was the best way to implement this. It was a pretty quick and dirty fix.

### CODE REVIEW

**Comment by jethrokuan** [comment]
This would make the theme only useful for `ox-hugo` users.

I think a better approach would be to extract the asset folder as a parameter in the toml config, and pass it in.

**Comment by AlexanderDavid** [comment]
Do you have any ideas of how to do this? I can't find anything about it in the hugo directory. What do you think about defining a list of extensions (e.g. `["pdf", "png", ...]`) that would be opened normally rather than in a stacked note?

**Comment by AlexanderDavid** [comment]
Accidentally pull requested with my master branch. I will update a new branch with the changes when you tell me what you think is the best approach

**Comment by jethrokuan** [comment]
I made some changes to the prefetching logic, that checks for content-type, so this issue should have gone away.

**Pull request closed without merging**
